/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ecw.student.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the StudentInfo service. Represents a row in the &quot;StudentInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ecw.student.model.impl.StudentInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ecw.student.model.impl.StudentInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentInfo
 * @see com.ecw.student.model.impl.StudentInfoImpl
 * @see com.ecw.student.model.impl.StudentInfoModelImpl
 * @generated
 */
@ProviderType
public interface StudentInfoModel extends BaseModel<StudentInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student info model instance should use the {@link StudentInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this student info.
	 *
	 * @return the primary key of this student info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student info.
	 *
	 * @param primaryKey the primary key of this student info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this student info.
	 *
	 * @return the ID of this student info
	 */
	public long getId();

	/**
	 * Sets the ID of this student info.
	 *
	 * @param Id the ID of this student info
	 */
	public void setId(long Id);

	/**
	 * Returns the student ID of this student info.
	 *
	 * @return the student ID of this student info
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student info.
	 *
	 * @param StudentId the student ID of this student info
	 */
	public void setStudentId(long StudentId);

	/**
	 * Returns the first name of this student info.
	 *
	 * @return the first name of this student info
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this student info.
	 *
	 * @param FirstName the first name of this student info
	 */
	public void setFirstName(String FirstName);

	/**
	 * Returns the last name of this student info.
	 *
	 * @return the last name of this student info
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this student info.
	 *
	 * @param LastName the last name of this student info
	 */
	public void setLastName(String LastName);

	/**
	 * Returns the blood group of this student info.
	 *
	 * @return the blood group of this student info
	 */
	@AutoEscape
	public String getBloodGroup();

	/**
	 * Sets the blood group of this student info.
	 *
	 * @param BloodGroup the blood group of this student info
	 */
	public void setBloodGroup(String BloodGroup);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StudentInfo studentInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StudentInfo> toCacheModel();

	@Override
	public StudentInfo toEscapedModel();

	@Override
	public StudentInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}